// Freshness guard for the baked /ask corpus: src/help/docs-bundle.ts is
// generated by scripts/gen-docs.mjs from the source docs and silently goes
// stale when someone edits a doc without re-running the script. This test
// applies the script's exact transform (readFileSync(file).trim(); empty or
// missing → skipped) and asserts the bundle matches byte-for-byte.
import { test, expect } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { DOCS_BUNDLE } from "../src/help/docs-bundle.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
// Must mirror the `files` list in scripts/gen-docs.mjs.
const SOURCES = ["README.md", "CLAUDE.md", "DESIGN.md", "experiments/FINDINGS.md"];

const STALE = "docs-bundle.ts is stale — run: node scripts/gen-docs.mjs";

test("docs-bundle.ts matches the source docs (gen-docs.mjs transform)", () => {
  const bundled = new Map(DOCS_BUNDLE.map((d) => [d.file, d.text]));
  const expected: string[] = [];
  for (const rel of SOURCES) {
    const abs = resolve(root, rel);
    if (!existsSync(abs)) continue; // gen-docs skips missing docs
    const text = readFileSync(abs, "utf8").trim();
    if (!text) continue; // gen-docs skips empty docs
    expected.push(rel);
    expect(bundled.has(rel), `${rel} missing from DOCS_BUNDLE — ${STALE}`).toBe(true);
    expect(bundled.get(rel) === text, `${rel} content differs from DOCS_BUNDLE — ${STALE}`).toBe(true);
  }
  // No phantom entries for docs that no longer exist (or went empty) on disk.
  for (const d of DOCS_BUNDLE) {
    expect(expected.includes(d.file), `${d.file} is in DOCS_BUNDLE but not a live source doc — ${STALE}`).toBe(true);
  }
});
