// "Ask Gearbox about Gearbox" — answer questions about the tool itself from the
// docs that ship with it (CLAUDE.md / DESIGN.md / README.md / FINDINGS.md), via a
// cheap model on the user's own keys (routed through the seam, kind:"search").
//
// The four docs total ~77k chars (~20k tokens), and the whole corpus goes in the
// system prompt — simpler and strictly more accurate than chunk retrieval at this
// scale. (An earlier 48k-char cap silently dropped FINDINGS.md; the cap below must
// always hold all four docs.)
// Docs are BAKED into the bundle (src/help/docs-bundle.ts, generated by
// scripts/gen-docs.mjs) so /ask works in the published single-file binary, which
// ships only dist/cli.mjs and none of the .md files.
import type { ModelMessage } from "ai";
import { DOCS_BUNDLE } from "./docs-bundle.ts";
import { helpText, ACCOUNT_ADD_HELP } from "../commands.ts";
import type { TurnMeta } from "../session.ts";

// Chars across all docs. The four docs total ~77k chars and FINDINGS must not be
// silently dropped; cheap routed models hold 110k chars (~30k tokens) fine.
const TOTAL_CAP = 110_000;

let cached: string | null = null;

/** The bundled Gearbox docs, concatenated with per-file headers, capped. "" if none. */
export function loadGearboxDocs(): string {
  if (cached !== null) return cached;
  const parts: string[] = [];
  let used = 0;
  for (const { file, text } of DOCS_BUNDLE) {
    if (!text) continue;
    const remaining = TOTAL_CAP - used;
    if (remaining <= 0) break;
    const body = text.length > remaining ? text.slice(0, remaining) + "\n…(truncated)" : text;
    parts.push(`# ${file}\n\n${body}`);
    used += body.length;
  }
  // The exact in-app command surface (slash commands + how to add accounts) lives
  // in code, not the markdown — without it the model can't answer "how do I add X"
  // precisely and will invent commands. Generate it so it's always accurate.
  parts.push(`# Command reference (in-app slash commands)\n\n${helpText()}\n\n${ACCOUNT_ADD_HELP}`);
  cached = parts.join("\n\n---\n\n");
  return cached;
}

/** Reset the doc cache (tests). */
export function resetDocsCache(): void {
  cached = null;
}

/** System prompt: answer ONLY from the bundled docs (plus the current-session
 *  facts when provided), concretely, or say you can't. */
export function buildAskSystem(docs: string, session?: string): string {
  return [
    "You answer questions about Gearbox, a multi-provider coding agent for the terminal.",
    session
      ? "Use ONLY the documentation and current-session facts below. Be concise and concrete: when a question is about"
      : "Use ONLY the documentation below. Be concise and concrete: when a question is about",
    "how to do something, quote the exact command, flag, or keybinding. If the answer is",
    "not in the docs, say so plainly and suggest the user run /help. Do not invent features.",
    "",
    "=== GEARBOX DOCUMENTATION ===",
    docs,
    ...(session
      ? ["", "=== CURRENT SESSION (recent turns + the model that answered each) ===", session]
      : []),
  ].join("\n");
}

/** Compact digest of the live session for /ask: the last few user/assistant
 *  exchanges plus which model served each turn (from the per-turn routing
 *  records), so "which model answered my last question" has a real answer.
 *  Pure; "" when the session has no completed exchanges. When the exchange and
 *  turn counts disagree (compaction, delegate sub-turns), per-exchange model
 *  attribution would be a guess — fall back to a separate ordered model list. */
export function sessionDigest(messages: ModelMessage[], turns: TurnMeta[], max = 6): string {
  const clip = (s: string, n = 100): string => {
    const t = s.replace(/\s+/g, " ").trim();
    return t.length > n ? t.slice(0, n - 1) + "…" : t;
  };
  // Text parts ONLY — deliberately not context/builder.ts textOf, which
  // stringifies tool-call inputs/results (a write_file call carries a whole
  // file; megabytes flattened just to clip to 100 chars, and JSON noise in
  // the digest besides).
  const textOnly = (content: unknown): string =>
    typeof content === "string"
      ? content
      : Array.isArray(content)
        ? content.map((p: any) => (typeof p === "string" ? p : p?.type === "text" ? p.text ?? "" : "")).join(" ")
        : "";
  const exchanges: { user: string; assistant: string }[] = [];
  let cur: { user: string; assistant: string } | null = null;
  for (const m of messages) {
    if (m.role === "user") {
      cur = { user: clip(textOnly(m.content)), assistant: "" };
      exchanges.push(cur);
    } else if (m.role === "assistant" && cur) {
      const t = clip(textOnly(m.content));
      if (t) cur.assistant = t; // last text wins (tool-call rounds precede it)
    }
  }
  const done = exchanges.filter((e) => e.assistant);
  if (!done.length) return "";
  const paired = done.length === turns.length;
  const recent = done.slice(-max);
  const recentTurns = turns.slice(-max);
  const modelOf = (t: TurnMeta | undefined): string => t?.servedModel ?? t?.model ?? "unknown";
  const lines = recent.map((e, i) => {
    const n = done.length - recent.length + i + 1;
    const via = paired ? ` (answered by ${modelOf(recentTurns[i])})` : "";
    return `${n}. user: "${e.user}" → assistant${via}: "${e.assistant}"`;
  });
  if (!paired && turns.length) {
    lines.push(`models that served the recent turns, oldest → newest: ${recentTurns.map(modelOf).join(", ")}`);
  }
  return lines.join("\n");
}

// Auto-detect: is this plain message a question ABOUT Gearbox (not a coding task
// on the user's own repo)? Precision over recall — a false negative just means the
// user types /ask; a false positive is shown with an affordance and is one rephrase
// from the real agent. So we only fire when it clearly reads as a meta-question.
const QUESTION_START = /^(how|what|where|why|which|can|does|do|is|are)\b/;
const TOOL_TERMS = /\bgearbox\b|\brouting\b|\broute\b|\bmodel(s)?\b|\baccount(s)?\b|\beffort\b|\bplan mode\b|\byolo\b|\bshortcut(s)?\b|\bkeybind|\bghost\b|\bboo\b|\bsession(s)?\b|\bcompact\b|\bmcp\b|\bprovider(s)?\b|\bapi key\b|\bfullscreen\b|\binline\b|\bsubscription\b/i;
const SLASH_CMD = /(^|\s)\/[a-z]/;
// Concrete signals the message is about the user's OWN code, not Gearbox — bail.
// NOT bare verbs like "add"/"create": those appear in legit how-tos ("how do I
// add an account?"). Only a file path / code fence / code noun disqualifies.
const CODE_SIGNAL =
  /```|\bthis (file|function|bug|code|repo|method|class)\b|\bthe bug\b|[\w./-]+\.(ts|tsx|js|jsx|py|go|rs|java|rb|md|json|ya?ml|css|html)\b|\b(function|class|variable|component|endpoint|cache|regex|schema|migration|dependency|import|module)\b/i;
// Questions about THIS conversation ("which model did you use…", "the question
// above") need session history — run them as a normal turn, never doc-grounded.
const CONVO_SIGNAL =
  /\b(you|your)\b.{0,40}\b(use|used|say|said|answer|answered|pick|picked|chose|choose|respond|responded)\b|\babove\b|\bearlier\b|\bprevious(ly)?\b|\blast (question|answer|response|message|turn)\b/i;

export function looksLikeGearboxQuestion(text: string): boolean {
  const t = text.trim();
  if (t.length < 6 || t.length > 240) return false;
  if (CODE_SIGNAL.test(t)) return false;
  if (CONVO_SIGNAL.test(t)) return false;
  const isQuestion = t.endsWith("?") || QUESTION_START.test(t.toLowerCase());
  if (!isQuestion) return false;
  return TOOL_TERMS.test(t) || SLASH_CMD.test(t);
}
