// "Ask Gearbox about Gearbox" — answer questions about the tool itself from the
// docs that ship with it (CLAUDE.md / DESIGN.md / README.md / FINDINGS.md), via a
// cheap model on the user's own keys (routed through the seam, kind:"search").
//
// The four docs total ~77k chars (~20k tokens), and the whole corpus goes in the
// system prompt — simpler and strictly more accurate than chunk retrieval at this
// scale. (An earlier 48k-char cap silently dropped FINDINGS.md; the cap below must
// always hold all four docs.)
// Docs are BAKED into the bundle (src/help/docs-bundle.ts, generated by
// scripts/gen-docs.mjs) so /ask works in the published single-file binary, which
// ships only dist/cli.mjs and none of the .md files.
import { DOCS_BUNDLE } from "./docs-bundle.ts";
import { helpText, ACCOUNT_ADD_HELP } from "../commands.ts";

// Chars across all docs. The four docs total ~77k chars and FINDINGS must not be
// silently dropped; cheap routed models hold 110k chars (~30k tokens) fine.
const TOTAL_CAP = 110_000;

let cached: string | null = null;

/** The bundled Gearbox docs, concatenated with per-file headers, capped. "" if none. */
export function loadGearboxDocs(): string {
  if (cached !== null) return cached;
  const parts: string[] = [];
  let used = 0;
  for (const { file, text } of DOCS_BUNDLE) {
    if (!text) continue;
    const remaining = TOTAL_CAP - used;
    if (remaining <= 0) break;
    const body = text.length > remaining ? text.slice(0, remaining) + "\n…(truncated)" : text;
    parts.push(`# ${file}\n\n${body}`);
    used += body.length;
  }
  // The exact in-app command surface (slash commands + how to add accounts) lives
  // in code, not the markdown — without it the model can't answer "how do I add X"
  // precisely and will invent commands. Generate it so it's always accurate.
  parts.push(`# Command reference (in-app slash commands)\n\n${helpText()}\n\n${ACCOUNT_ADD_HELP}`);
  cached = parts.join("\n\n---\n\n");
  return cached;
}

/** Reset the doc cache (tests). */
export function resetDocsCache(): void {
  cached = null;
}

/** System prompt: answer ONLY from the bundled docs, concretely, or say you can't. */
export function buildAskSystem(docs: string): string {
  return [
    "You answer questions about Gearbox, a multi-provider coding agent for the terminal.",
    "Use ONLY the documentation below. Be concise and concrete: when a question is about",
    "how to do something, quote the exact command, flag, or keybinding. If the answer is",
    "not in the docs, say so plainly and suggest the user run /help. Do not invent features.",
    "",
    "=== GEARBOX DOCUMENTATION ===",
    docs,
  ].join("\n");
}

// Auto-detect: is this plain message a question ABOUT Gearbox (not a coding task
// on the user's own repo)? Precision over recall — a false negative just means the
// user types /ask; a false positive is shown with an affordance and is one rephrase
// from the real agent. So we only fire when it clearly reads as a meta-question.
const QUESTION_START = /^(how|what|where|why|which|can|does|do|is|are)\b/;
const TOOL_TERMS = /\bgearbox\b|\brouting\b|\broute\b|\bmodel(s)?\b|\baccount(s)?\b|\beffort\b|\bplan mode\b|\byolo\b|\bshortcut(s)?\b|\bkeybind|\bghost\b|\bboo\b|\bsession(s)?\b|\bcompact\b|\bmcp\b|\bprovider(s)?\b|\bapi key\b|\bfullscreen\b|\binline\b|\bsubscription\b/i;
const SLASH_CMD = /(^|\s)\/[a-z]/;
// Concrete signals the message is about the user's OWN code, not Gearbox — bail.
// NOT bare verbs like "add"/"create": those appear in legit how-tos ("how do I
// add an account?"). Only a file path / code fence / code noun disqualifies.
const CODE_SIGNAL =
  /```|\bthis (file|function|bug|code|repo|method|class)\b|\bthe bug\b|[\w./-]+\.(ts|tsx|js|jsx|py|go|rs|java|rb|md|json|ya?ml|css|html)\b|\b(function|class|variable|component|endpoint|cache|regex|schema|migration|dependency|import|module)\b/i;

export function looksLikeGearboxQuestion(text: string): boolean {
  const t = text.trim();
  if (t.length < 6 || t.length > 240) return false;
  if (CODE_SIGNAL.test(t)) return false;
  const isQuestion = t.endsWith("?") || QUESTION_START.test(t.toLowerCase());
  if (!isQuestion) return false;
  return TOOL_TERMS.test(t) || SLASH_CMD.test(t);
}
