// Bake the Gearbox docs into a TS module so /ask has its corpus in the published
// single-file binary (the npm tarball ships only dist/cli.mjs, not the .md files).
// Same pattern as scripts/gen-mascot.ts. Run by `bun run build`; the output
// src/help/docs-bundle.ts is committed so dev + tests work without a build step.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const files = ["README.md", "CLAUDE.md", "DESIGN.md", "experiments/FINDINGS.md"];

const out = [];
for (const rel of files) {
  try {
    const text = readFileSync(resolve(root, rel), "utf8").trim();
    if (text) out.push({ file: rel, text });
  } catch {
    /* missing doc → skip */
  }
}

const body =
  "// AUTO-GENERATED by scripts/gen-docs.mjs — do not edit by hand.\n" +
  "// The bundled Gearbox docs, baked in so /ask works in the published binary.\n" +
  `export const DOCS_BUNDLE: { file: string; text: string }[] = ${JSON.stringify(out, null, 2)};\n`;

writeFileSync(resolve(root, "src/help/docs-bundle.ts"), body);
console.log(`baked ${out.length} docs → src/help/docs-bundle.ts`);
